from pymongo import ASCENDING, DESCENDING

from dotenv import dotenv_values

CONNECTION_CONFIG = dotenv_values('.env')

WSJTX_IP = CONNECTION_CONFIG['WSJTX_IP']
WSJTX_PORT = int(CONNECTION_CONFIG['WSJTX_PORT'])
MULTICAST = CONNECTION_CONFIG.get('MULTICAST', '').upper() in ['1', 'TRUE', 'YES', 'T','Y']

MONGO_HOST = CONNECTION_CONFIG['MONGO_HOST']
MONGO_PORT = int(CONNECTION_CONFIG['MONGO_PORT'])

REDIS_HOST = CONNECTION_CONFIG['REDIS_HOST']
REDIS_PORT = int(CONNECTION_CONFIG['REDIS_PORT'])

QRZ_API_KEY = CONNECTION_CONFIG.get('QRZ_API_KEY', '')
QRZ_USERNAME = CONNECTION_CONFIG.get('QRZ_USERNAME', '')
QRZ_PASSWORD = CONNECTION_CONFIG.get('QRZ_PASSWORD', '')

NUM_DAYS_LOG = 0

INCLUDE_NO_GRID_CQ = True

INCLUDE_CALLSIGN_WITH_AFFIX = False

NEW_GRID = True
NEW_DXCC = True
RR73_AS_CQ = True

WORK_ON_UNCONFIRMED_QSO = False

NUM_INACTIVE_BEFORE_CUT = 1

MAX_FORCE_REPLY_WHEN_BUSY = 2

MAX_TRIES_CHANGE_FREQUENCY = 2
MAX_TRIES = 3

MIN_DB = -17

MIN_FREQUENCY = 200
MAX_FREQUENCY = 2500

LOG_LOCATION = 'data/log.adi'

SORTBY = [
    ['timestamp', DESCENDING]
]

EXPIRED_TIME = 120

DXCC_EXCEPTION = [
    "Indonesia",
    "China",
    "Japan",
    "Republic of Korea"
]

CALLSIGN_EXCEPTION = 'data/Callsign_Exception.txt'